# Please read https://github.com/holtwick/briefing/blob/master/docs/docker.md for proper use of Docker

version: '3'

services:
  briefing:
    image: holtwick/briefing
    restart: always
    volumes:
      - ./data:/app/data
    ports:
      - 8080:8080

# networks:
#   default:
#     external:
#       name: proxy
